### ISSUE TITLE
Poco dependencies libz and libpcre not found

### ISSUE THREAD

**Issue by lmayencourt** [ros2/cross_compile#11]
The packages depending on the Poco libraries fails if the pre-built binaries of Poco are used:
The `PocoFoundationTargets.cmake` file coming with the pre-built binaries have an hard-coded paths to `/usr/lib/<arch>/libz.so` and `/usr/lib/<arch>/libpcre.so` which makes the cross-compilation to fail.

The current workaround use symbolic links to the libz and libpcre libraries on `/usr/lib/<arch>/` pointing to the actual libraries on the target filesystem.

A ongoing PR on the Poco project should fix this issue: https://github.com/pocoproject/poco/pull/2599

**Comment by Bjoe** [comment]
https://github.com/pocoproject/poco/pull/2679 and https://github.com/pocoproject/poco/pull/2679 is merged now. This should fix your issue here :-).

**Comment by filiperinaldi** [comment]
Thanks @Bjoe and @lmayencourt.
We will remove the workaround in https://github.com/ros2/cross_compile/blob/3e6200560e512d6d7bb313d380fa6982d8bdaab7/entry_point.sh#L38 once the fixes are available on the next Poco release.
