### ISSUE TITLE
Update instructions for ROS2 Crystal

### ISSUE THREAD

**Issue by jpsamper2009** [ros2/cross_compile#14]
The following line makes me suspect that [the instructions](https://index.ros.org/doc/ros2/Tutorials/Cross-compilation) haven't been fully updated for ROS2 Crystal: https://github.com/ros2/cross_compile/blob/master/sysroot/Dockerfile_ubuntu_arm#L75

**Comment by lmayencourt** [comment]
ho yes, nice catch !
Can you please create a PR to update this ?

**Comment by filiperinaldi** [comment]
Fix merged (#16)
